/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class columbus_licence_Licence */

#ifndef _Included_columbus_licence_Licence
#define _Included_columbus_licence_Licence
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     columbus_licence_Licence
 * Method:    checkLicence
 * Signature: (Ljava/lang/String;Lcolumbus/Version;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_columbus_licence_Licence_checkLicence
  (JNIEnv *, jclass, jstring, jobject, jstring);

/*
 * Class:     columbus_licence_Licence
 * Method:    checkLicenceFile
 * Signature: (Ljava/lang/String;Lcolumbus/Version;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_columbus_licence_Licence_checkLicenceFile__Ljava_lang_String_2Lcolumbus_Version_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jobject, jstring);

/*
 * Class:     columbus_licence_Licence
 * Method:    checkLicenceFile
 * Signature: (Ljava/lang/String;Lcolumbus/Version;)Z
 */
JNIEXPORT jboolean JNICALL Java_columbus_licence_Licence_checkLicenceFile__Ljava_lang_String_2Lcolumbus_Version_2
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
