#ifndef _COLUMBUS_ENVIRONMENT_H_
#define _COLUMBUS_ENVIRONMENT_H_

#define IN_COLUMBUS_REGTEST_ENV_VAR              "IN_COLUMBUS_REGTEST"
#define COLUMBUS_RUN_DEBUG_ENV_VAR               "COLUMBUS_RUN_DEBUG"
#define COLUMBUS_EXEWRAPPER_DEBUG_ENV_VAR        "COLUMBUS_EXEWRAPPER_DEBUG"

#define COLUMBUS_LICENSE_SERVER_ENV_VAR          "COLUMBUS_LICENSE_SERVER"
#define COLUMBUS_LICENSE_FILE_ENV_VAR            "COLUMBUS_LICENSE_FILE"
#define COLUMBUS_LICENSE_SERVER_TIMEOUT_ENV_VAR  "COLUMBUS_LICENSE_SERVER_TIMEOUT"
#define COLUMBUS_LICENSE_SERVER_RETRY_ENV_VAR    "COLUMBUS_LICENSE_SERVER_RETRY"
#define COLUMBUS_LICENSE_SERVER_UUID_VAR         "COLUMBUS_LICENSE_SERVER_UUID"

#define ANALYZER_WRAPPER_CONFIG_FILE_ENV_VAR     "ANALYZER_CONFIG_FILE"
#define ANALYZER_INEXEWRAPPER_ENV_VAR            "ANALYZER_IN_EXEWRAPPER"

#define COLUMBUS_VERBOSE_CURL_VAR                "COLUMBUS_VERBOSE_CURL"

#define LIBCLANG_ALLOW_PCH_WITH_ERRORS_VAR       "LIBCLANG_ALLOW_PCH_WITH_COMPILER_ERRORS"

#define COLUMBUS_ANALYZER_IS_ACTIVE              "ANALYZER_IS_ACTIVE"

#endif

